version: '3.9'

services:
  djangoapp:
    build: ./
    restart: always
    volumes:
    #  - ./db.sqlite3:/code/db.sqlite3 # use this to use local db.sqlite3 with DEBUG=1 set
      - static-data:/code/collectstatic
      - media-data:/code/media
    environment:
      - DB_HOST=db
      - ENABLE_REDIS=1
      - PROXY_HTTPS=1
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - nginx

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./nginx/:/etc/nginx/conf.d
    - ./certs:/etc/nginx/certs
    - static-data:/opt/services/djangoapp/static
    - media-data:/opt/services/djangoapp/media

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
  media-data:
  static-data:
