# Generated by Django 3.2.9 on 2021-12-30 18:58

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_meeting_id', models.PositiveIntegerField()),
                ('response', models.SmallIntegerField(default=0)),
                ('question', models.CharField(max_length=1000)),
                ('options', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['meeting_id', 'per_meeting_id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to=api.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreationSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(default=api.models.generate_random_password, max_length=200)),
                ('valid_until', models.DateTimeField(default=api.models.generate_valid_until)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(unique=True)),
                ('password_cleartext', models.CharField(default=api.models.generate_random_password, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenshot_path', models.CharField(default=api.models.get_random_screenshot_path, max_length=100)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.meetingvideo')),
            ],
        ),
        migrations.CreateModel(
            name='DataShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_meeting_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1650)),
                ('frm', models.FloatField()),
                ('to', models.FloatField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
            options={
                'ordering': ['meeting_id', 'per_meeting_id'],
                'unique_together': {('meeting_id', 'per_meeting_id')},
            },
        ),
        migrations.CreateModel(
            name='DataPollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.PositiveIntegerField()),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datapoll')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
        ),
        migrations.AddField(
            model_name='datapoll',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting'),
        ),
        migrations.AddField(
            model_name='datapoll',
            name='shot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datashot'),
        ),
        migrations.CreateModel(
            name='DataUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_meeting_id', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=30)),
                ('capability', models.CharField(max_length=3300)),
                ('benefit', models.CharField(max_length=3300)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
                ('shot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datashot')),
            ],
            options={
                'ordering': ['meeting_id', 'per_meeting_id'],
                'unique_together': {('meeting_id', 'per_meeting_id')},
            },
        ),
        migrations.CreateModel(
            name='DataSatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_meeting_id', models.PositiveIntegerField()),
                ('satz', models.CharField(max_length=3300)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
                ('shot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datashot')),
            ],
            options={
                'ordering': ['meeting_id', 'per_meeting_id'],
                'unique_together': {('meeting_id', 'per_meeting_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='datapoll',
            unique_together={('meeting_id', 'per_meeting_id')},
        ),
        migrations.CreateModel(
            name='DataAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_meeting_id', models.PositiveIntegerField()),
                ('pos_x', models.PositiveIntegerField()),
                ('pos_y', models.PositiveBigIntegerField()),
                ('titel', models.CharField(max_length=1000)),
                ('text_type', models.SmallIntegerField(default=0)),
                ('text', models.CharField(max_length=1000)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
                ('shot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datashot')),
            ],
            options={
                'ordering': ['meeting_id', 'per_meeting_id'],
                'unique_together': {('meeting_id', 'per_meeting_id')},
            },
        ),
    ]
